In [241]:
#importer les librairies
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [264]:
#charger le dataset
df=pd.read_csv('iris.csv', sep=',',decimal='.')

In [265]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [266]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [267]:
#encodage
#df['species'].replace(['setosa', 'versicolor', 'virginica'], [0,1,2], inplace=True)

In [268]:
#affectation
X= df[['sepal_length','sepal_width','petal_length','petal_width']]
y=df['species']

In [247]:
#diviser le jeu de données avec le train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.2, random_state=101)

In [248]:
X_test.shape

(30, 4)

In [249]:
#créer le modèle
from sklearn.ensemble import RandomForestClassifier

In [250]:
model=RandomForestClassifier(n_estimators=400)
model.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=400,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [251]:
y_pred=model.predict(X_test)

In [252]:
y_pred

array(['setosa', 'setosa', 'setosa', 'virginica', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'setosa', 'virginica', 'virginica',
       'versicolor', 'versicolor', 'versicolor', 'setosa', 'versicolor',
       'versicolor', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'virginica', 'setosa', 'setosa'],
      dtype=object)

In [253]:
#importer les modules d'évaluation
from sklearn.metrics import classification_report, confusion_matrix

In [254]:
print(confusion_matrix(y_pred,y_test))

[[10  0  0]
 [ 0 12  1]
 [ 0  0  7]]


In [255]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.92      0.96        13
   virginica       0.88      1.00      0.93         7

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



In [256]:
#serialisation
import pickle

In [257]:
pickle_out=(open('modeliris.pkl','wb'))
pickle.dump(model,pickle_out)
pickle_out.close()

In [258]:
test=pickle.load(open('modeliris.pkl','rb'))

In [259]:
 model.predict_proba([[3,2.5,1,0.5]])

array([[0.9525, 0.04  , 0.0075]])

In [260]:
from sklearn.externals import joblib

In [261]:
joblib.dump(model,'model2.pkl')

['model2.pkl']

In [262]:
test2=joblib.load('model2.pkl')

In [263]:
test2.predict_proba([[3,2.5,1,0.5]])

array([[0.9525, 0.04  , 0.0075]])